// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsApi.Data;

#nullable disable

namespace StudentsApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20230515144709_m4")]
    partial class m4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("StudentsApi.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Tom",
                            LastName = "Max",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Ann",
                            LastName = "Fay",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Joe",
                            LastName = "Sun",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Sue",
                            LastName = "Fox",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Ben",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstName = "Zoe",
                            LastName = "Cox",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 7,
                            FirstName = "Sam",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 8,
                            FirstName = "Dan",
                            LastName = "Ash",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 9,
                            FirstName = "Pat",
                            LastName = "Lee",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 10,
                            FirstName = "Kim",
                            LastName = "Day",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 11,
                            FirstName = "Tim",
                            LastName = "Rex",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 12,
                            FirstName = "Rob",
                            LastName = "Ram",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 13,
                            FirstName = "Jan",
                            LastName = "Fry",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 14,
                            FirstName = "Jim",
                            LastName = "Tex",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 15,
                            FirstName = "Ben",
                            LastName = "Kid",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 16,
                            FirstName = "Mia",
                            LastName = "Chu",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 17,
                            FirstName = "Ted",
                            LastName = "Tao",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 18,
                            FirstName = "Amy",
                            LastName = "Day",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 19,
                            FirstName = "Ian",
                            LastName = "Roy",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 20,
                            FirstName = "Liz",
                            LastName = "Kit",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 21,
                            FirstName = "Mat",
                            LastName = "Tan",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 22,
                            FirstName = "Deb",
                            LastName = "Roy",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 23,
                            FirstName = "Ana",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 24,
                            FirstName = "Lyn",
                            LastName = "Poe",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 25,
                            FirstName = "Amy",
                            LastName = "Raj",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 26,
                            FirstName = "Kim",
                            LastName = "Ash",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 27,
                            FirstName = "Bec",
                            LastName = "Kid",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 28,
                            FirstName = "Eva",
                            LastName = "Fry",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 29,
                            FirstName = "Eli",
                            LastName = "Lap",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 30,
                            FirstName = "Sam",
                            LastName = "Yim",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 31,
                            FirstName = "Joe",
                            LastName = "Hui",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 32,
                            FirstName = "Liz",
                            LastName = "Jin",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 33,
                            FirstName = "Ric",
                            LastName = "Kuo",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 34,
                            FirstName = "Pam",
                            LastName = "Mak",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 35,
                            FirstName = "Cat",
                            LastName = "Yao",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 36,
                            FirstName = "Lou",
                            LastName = "Zhu",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 37,
                            FirstName = "Tom",
                            LastName = "Dag",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 38,
                            FirstName = "Stu",
                            LastName = "Day",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 39,
                            FirstName = "Tom",
                            LastName = "Gad",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 40,
                            FirstName = "Bob",
                            LastName = "Bee",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 41,
                            FirstName = "Jim",
                            LastName = "Ots",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 42,
                            FirstName = "Tom",
                            LastName = "Mag",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 43,
                            FirstName = "Hal",
                            LastName = "Doe",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 44,
                            FirstName = "Roy",
                            LastName = "Kim",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 45,
                            FirstName = "Vis",
                            LastName = "Cox",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 46,
                            FirstName = "Kay",
                            LastName = "Aga",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 47,
                            FirstName = "Reo",
                            LastName = "Hui",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 48,
                            FirstName = "Bob",
                            LastName = "Roe",
                            School = "Mining"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
